version: '3.0'

expectations:

  population_size: 500000


actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
    outputs:
      highly_sensitive:
        cohort_vaccinated: output/input_vaccinated.rds
        cohort_electively_unvaccinated: output/input_electively_unvaccinated.rds
        venn_vaccinated: output/venn_vaccinated.rds
        venn_electively_unvaccinated: output/venn_electively_unvaccinated.rds

  stage1_data_cleaning_electively_unvaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R output/input_electively_unvaccinated.rds electively_unvaccinated
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors_electively_unvaccinated.csv
        QA_rules: output/QA_summary_electively_unvaccinated.csv
        IE_criteria: output/Cohort_flow_electively_unvaccinated.csv
      highly_sensitive:
        cohort: output/input_electively_unvaccinated_stage1.rds

  stage1_data_cleaning_vaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R output/input_vaccinated.rds vaccinated
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors_vaccinated.csv
        QA_rules: output/QA_summary_vaccinated.csv
        IE_criteria: output/Cohort_flow_vaccinated.csv
      highly_sensitive:
        cohort: output/input_vaccinated_stage1.rds
  venn_diagram_vaccinated:
    run: r:latest analysis/venn_diagram.R vaccinated
    needs: [preprocess_data]
    outputs:
      highly_sensitive:
        acute_myocardial_infarction: output/vaccinated_f1_venn_ami.png
        ischaemic_stroke: output/vaccinated_f2_venn_stroke.png
        pulmonary_embolism: output/vaccinated_f3_venn_pe.png
        deep_vein_thrombosis: output/vaccinated_f4_venn_dvt.png
        transient_ischaemic_attack: output/vaccinated_f5_venn_tia.png
        subarachnoid_haemorrhage_and_haemorrhagic_stroke: output/vaccinated_f6_venn_stroke_sah_hs.png
        heart_failure: output/vaccinated_f7_venn_hf.png
        angina_pectoris: output/vaccinated_f8_venn_angina.png
        all_arterial_thrombotic_and_embolization_events: output/vaccinated_f9_venn_oae.png
        all_venous_thromboembolism_events: output/vaccinated_f10_venn_vte.png 

  venn_diagram_electively_unvaccinated:
    run: r:latest analysis/venn_diagram.R electively_unvaccinated
    needs: [preprocess_data]
    outputs:
      highly_sensitive:
        acute_myocardial_infarction: output/electively_unvaccinated_f1_venn_ami.png
        ischaemic_stroke: output/electively_unvaccinated_f2_venn_stroke.png
        pulmonary_embolism: output/electively_unvaccinated_f3_venn_pe.png
        deep_vein_thrombosis: output/electively_unvaccinated_f4_venn_dvt.png
        transient_ischaemic_attack: output/electively_unvaccinated_f5_venn_tia.png
        subarachnoid_haemorrhage_and_haemorrhagic_stroke: output/electively_unvaccinated_f6_venn_stroke_sah_hs.png
        heart_failure: output/electively_unvaccinated_f7_venn_hf.png
        angina_pectoris: output/electively_unvaccinated_f8_venn_angina.png
        all_arterial_thrombotic_and_embolization_events: output/electively_unvaccinated_f9_venn_oae.png
        all_venous_thromboembolism_events: output/electively_unvaccinated_f10_venn_vte.png 
  # venn_diagram_vaccinated:
  #   run: r:latest analysis/venn_diagram.R vaccinated
  #   needs: [preprocess_data]
  #   outputs:
  #     highly_sensitive:
  #       acute_myocardial_infarction: output/vaccinated_f1_venn_ami.png
  #       ischaemic_stroke: output/vaccinated_f2_venn_stroke.png
  #       pulmonary_embolism: output/vaccinated_f3_venn_pe.png
  #       deep_vein_thrombosis: output/vaccinated_f4_venn_dvt.png
  #       transient_ischaemic_attack: output/vaccinated_f5_venn_tia.png
  #       subarachnoid_haemorrhage_and_haemorrhagic_stroke: output/vaccinated_f6_stroke_sah_hs.png
  #       heart_failure: output/vaccinated_f7_venn_hf.png
  #       angina_pectoris: output/vaccinated_f8_venn_angina.png
  #       all_arterial_thrombotic_and_embolization_events: output/vaccinated_f9_venn_oae.png
  #       all_venous_thromboembolism_events: output/vaccinated_f10_venn_vte.png 

  # venn_diagram_electively_unvaccinated:
  #   run: r:latest analysis/venn_diagram.R electively_unvaccinated
  #   needs: [preprocess_data]
  #   outputs:
  #     highly_sensitive:
  #       acute_myocardial_infarction: output/electively_unvaccinated_f1_venn_ami.png
  #       ischaemic_stroke: output/electively_unvaccinated_f2_venn_stroke.png
  #       pulmonary_embolism: output/electively_unvaccinated_f3_venn_pe.png
  #       deep_vein_thrombosis: output/electively_unvaccinated_f4_venn_dvt.png
  #       transient_ischaemic_attack: output/electively_unvaccinated_f5_venn_tia.png
  #       subarachnoid_haemorrhage_and_haemorrhagic_stroke: output/electively_unvaccinated_f6_stroke_sah_hs.png
  #       heart_failure: output/electively_unvaccinated_f7_venn_hf.png
  #       angina_pectoris: output/electively_unvaccinated_f8_venn_angina.png
  #       all_arterial_thrombotic_and_embolization_events: output/electively_unvaccinated_f9_venn_oae.png
  #       all_venous_thromboembolism_events: output/electively_unvaccinated_f10_venn_vte.png 

  venn_diagram_electively_unvaccinated:
    run: r:latest analysis/venn_diagram.R electively_unvaccinated
    needs: [preprocess_data]
    outputs:
      highly_sensitive:
        acute_myocardial_infarction: output/electively_unvaccinated_f1_venn_ami.png
        ischaemic_stroke: output/electively_unvaccinated_f2_venn_stroke.png
        pulmonary_embolism: output/electively_unvaccinated_f3_venn_pe.png
        deep_vein_thrombosis: output/electively_unvaccinated_f4_venn_dvt.png
        transient_ischaemic_attack: output/electively_unvaccinated_f5_venn_tia.png
        subarachnoid_haemorrhage_and_haemorrhagic_stroke: output/electively_unvaccinated_f6_stroke_sah_hs.png
        heart_failure: output/electively_unvaccinated_f7_venn_hf.png
        angina_pectoris: output/electively_unvaccinated_f8_venn_angina.png
        all_arterial_thrombotic_and_embolization_events: output/electively_unvaccinated_f9_venn_oae.png
        all_venous_thromboembolism_events: output/electively_unvaccinated_f10_venn_vte.png 
