version: '3.0'

expectations:

  population_size: 500000


actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
    outputs:
      moderately_sensitive:
        describe: output/describe_*.txt
      highly_sensitive:
        cohort: output/input_*.rds
        venn: output/venn_*.rds

  stage1_data_cleaning_both:
    run: r:latest analysis/Stage1_data_cleaning.R both
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring_unvax: output/meta_data_factors_electively_unvaccinated.csv
        refactoring_vax: output/meta_data_factors_vaccinated.csv
        QA_rules_unvax: output/QA_summary_electively_unvaccinated.csv
        QA_rules_vax: output/QA_summary_vaccinated.csv
        IE_criteria_unvax: output/Cohort_flow_electively_unvaccinated.csv
        IE_criteria_vax: output/Cohort_flow_vaccinated.csv
      highly_sensitive:
        cohort_unvax: output/input_electively_unvaccinated_stage1.rds
        cohort_vax: output/input_vaccinated_stage1.rds

  stage2_missing_table1_both:
    run: r:latest analysis/Stage2_missing_table1.R both
    needs: [stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        Missing_RangeChecks_unvax: output/Check_missing_range_electively_unvaccinated.csv
        DateChecks_unvax: output/Check_dates_range_electively_unvaccinated.csv
        Descriptive_Table_unvax: output/Table1_electively_unvaccinated.csv
        Missing_RangeChecks_vax: output/Check_missing_range_vaccinated.csv
        DateChecks_vax: output/Check_dates_range_vaccinated.csv
        Descriptive_Table_vax: output/Table1_vaccinated.csv
