version: '3.0'

expectations:

  population_size: 500000

actions:
  active_analyses:
    run: r:latest analysis/active_analyses.R
    outputs:
      highly_sensitive:
        active_analyses: output/active_analyses.rds

  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
    outputs:
      moderately_sensitive:
        describe: output/describe_*.txt
      highly_sensitive:
        cohort: output/input_*.rds
        venn: output/venn_*.rds

  stage1_data_cleaning_both:
    run: r:latest analysis/Stage1_data_cleaning.R both
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors_*.csv
        QA_rules: output/QA_summary_*.csv
        IE_criteria: output/Cohort_flow_*.csv
      highly_sensitive:
        cohort: output/input_*_stage1.rds

  stage2_missing_table1_both:
    run: r:latest analysis/Stage2_missing_table1.R both
    needs: [stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        Missing_RangeChecks: output/Check_missing_range_*.csv
        DateChecks: output/Check_dates_range_*.csv
        Descriptive_Table: output/Table1_*.csv
  
  analysis_cox_ami:
    run: r:latest analysis/01_pipe.R ami
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_ami.html
        compiled_event_counts_html: output/compiled_event_counts_ami.html
        analyses_not_run: output/analyses_not_run_ami.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_ami.csv
        compiled_event_counts_csv: output/compiled_event_counts_ami.csv

  analysis_cox_stroke_isch:
    run: r:latest analysis/01_pipe.R stroke_isch
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_stroke_isch.html
        compiled_event_counts_html: output/compiled_event_counts_stroke_isch.html
        analyses_not_run: output/analyses_not_run_stroke_isch.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_stroke_isch.csv
        compiled_event_counts_csv: output/compiled_event_counts_stroke_isch.csv

  analysis_cox_dvt:
    run: r:latest analysis/01_pipe.R dvt
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs: output/compiled_HR_results_dvt.html
        compiled_event_counts: output/compiled_event_counts_dvt.html
        analyses_not_run: output/analyses_not_run_dvt.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_dvt.csv
        compiled_event_counts_csv: output/compiled_event_counts_dvt.csv

  analysis_cox_pe:
    run: r:latest analysis/01_pipe.R pe
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_pe.html
        compiled_event_counts_html: output/compiled_event_counts_pe.html
        analyses_not_run: output/analyses_not_run_pe.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_pe.csv
        compiled_event_counts_csv: output/compiled_event_counts_pe.csv

  analysis_cox_tia:
    run: r:latest analysis/01_pipe.R tia
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_tia.html
        compiled_event_counts_html: output/compiled_event_counts_tia.html
        analyses_not_run: output/analyses_not_run_tia.csv
      highly_sensitive:
         compiled_hrs_csv: output/compiled_HR_results_tia.csv
         compiled_event_counts_csv: output/compiled_event_counts_tia.csv

  analysis_cox_stroke_sah_hs:
    run: r:latest analysis/01_pipe.R stroke_sah_hs
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_stroke_sah_hs.html
        compiled_event_counts_html: output/compiled_event_counts_stroke_sah_hs.html
        analyses_not_run: output/analyses_not_run_stroke_sah_hs.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_stroke_sah_hs.csv
        compiled_event_counts_csv: output/compiled_event_counts_stroke_sah_hs.csv

  analysis_cox_hf:
    run: r:latest analysis/01_pipe.R hf
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_hf.html
        compiled_event_counts_html: output/compiled_event_counts_hf.html
        analyses_not_run: output/analyses_not_run_hf.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_hf.csv
        compiled_event_counts_csv: output/compiled_event_counts_hf.csv

  analysis_cox_angina:
    run: r:latest analysis/01_pipe.R angina
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_angina.html
        compiled_event_counts_html: output/compiled_event_counts_angina.html
        analyses_not_run: output/analyses_not_run_angina.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_angina.csv
        compiled_event_counts_csv: output/compiled_event_counts_angina.csv

  analysis_cox_ate:
    run: r:latest analysis/01_pipe.R ate
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_ate.html
        compiled_event_counts_html: output/compiled_event_counts_ate.html
        analyses_not_run: output/analyses_not_run_ate.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_ate.csv
        compiled_event_counts_csv: output/compiled_event_counts_ate.csv

  analysis_cox_vte:
    run: r:latest analysis/01_pipe.R vte
    needs: [active_analyses,stage1_data_cleaning_both]
    outputs:
      moderately_sensitive:
        compiled_hrs_html: output/compiled_HR_results_vte.html
        compiled_event_counts_html: output/compiled_event_counts_vte.html
        analyses_not_run: output/analyses_not_run_vte.csv
      highly_sensitive:
        compiled_hrs_csv: output/compiled_HR_results_vte.csv
        compiled_event_counts_csv: output/compiled_event_counts_vte.csv

  supplementary_table_1:
    run: r:latest analysis/Supplementary_table_1.R
    needs: [active_analyses,analysis_cox_ami,analysis_cox_stroke_isch,analysis_cox_dvt,analysis_cox_pe,analysis_cox_tia,analysis_cox_stroke_sah_hs,analysis_cox_hf,analysis_cox_angina,analysis_cox_ate,analysis_cox_vte]
    outputs:
      moderately_sensitive:
        supplementary_table_1_csv: output/supplementary_table_1.csv
        less_than_5_events_supplementary_table_1_csv: output/less_than_5_events_supplementary_table_1.csv
        supplementary_table_1_html: output/supplementary_table_1.html
        less_than_5_events_supplementary_table_1_html: output/less_than_5_events_supplementary_table_1.html