version: '3.0'

expectations:
  population_size: 100000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    needs:
    - vax_eligibility_inputs 
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input.rds

  stage1_data_cleaning_vaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R input.rds "vaccinated"
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: meta_data_factors_vaccinated.csv
        QA_rules: QA_summary_vaccinated.csv
        IE_criteria: Cohort_flow_vaccinated.csv
      highly_sensitive:
        cohort: output/dataset_stage1_vaccinated.rds

  stage1_data_cleaning_electively_unvaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R input.rds "electively_unvaccinated"
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: meta_data_factors_electively_unvaccinated.csv
        QA_rules: QA_summary_electively_unvaccinated.csv
        IE_criteria: Cohort_flow_electively_unvaccinated.csv
      highly_sensitive:
        cohort: output/dataset_stage1_velectively_unaccinated.rds