version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  preprocess_data:
    run: r:latest analysis/00-preprocess_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input.rds
